name: counter_recorder_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: vladimir.minkin <email@example.com>

environment:
  sdk: '^3.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  framework:
    path: ./framework

  idb_shim: ^2.3.1

dev_dependencies:
  intl: ^0.18.1
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.5
